version: '3.8'

services:
  backend:
    build:
      context: ./fabarblog
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=fabarblog_db;Username=blogger;Password=123456
    depends_on:
      - db
    volumes:
      - ./fabarblog:/src
    command: dotnet watch run

  frontend:
    build:
      context: ./fabarblog-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./fabarblog-frontend:/app
      - /app/node_modules

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=fabarblog_db
      - POSTGRES_USER=blogger
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
